upward-growth-plants:
  - SUGAR_CANE
  - CACTUS
  - BAMBOO
  - KELP
  - KELP_PLANT
  - TWISTING_VINES
  - TWISTING_VINES_PLANT
  - BAMBOO_SAPLING

downward-growth-plants:
  - VINE
  - WEEPING_VINES
  - WEEPING_VINES_PLANT
  - CAVE_VINES
  - CAVE_VINES_PLANT
  - GLOW_BERRIES

shear-sound-plants:
  - SUGAR_CANE
  - CACTUS

messages:
  disable-growth: "&cGrowth disabled for this plant."
  enable-growth: "&aGrowth enabled for this plant."
