name: StopPlantGrowth
version: '1.0.0'
main: io.github.aplini.StopPlantGrowth.StopPlantGrowth
api-version: '1.21'
authors: [ ApliNi ]
website: https://github.com/aplini/
description: Toggle growth locking for vines and other vertical plants using shears.

commands:
  igc:
    description: Main command for StopPlantGrowth.
    usage: /igc <reload|chunk|clear [radius]>
    aliases: [stopplantgrowth]

permissions:

  StopPlantGrowth.reload:
    description: Reloads StopPlantGrowth configuration.
    default: op

  StopPlantGrowth.chunk:
    description: Lists locked plants in the player's current chunk.
    default: op

  StopPlantGrowth.clear:
    description: Clears locked plants around the player using a radius from 1 to 5.
    default: op
